### ISSUE TITLE
Apache licesne, please

### ISSUE THREAD

**Issue by jameshensman** [ChenMnZ/PrefixQuant#10]
Hi PrefixQuant authors!

I'm an author of QuaRot https://github.com/spcl/QuaRot

Congrats on a nice paper! We're really happy that you built on QuaRot, and I enjoyed reading your contribution. 

In building on QuaRot, it looks like you used a bunch of our code. This is fine, and is the reason we released the code. But you must comply with the Apache license wherever you have used our code. In particular:

```
   4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:
 
      (a) You must give any other recipients of the Work or
          Derivative Works a copy of this License; and
 
      (b) You must cause any modified files to carry prominent notices
          stating that You changed the files; and
 
      (c) You must retain, in the Source form of any Derivative Works
          that You distribute, all copyright, patent, trademark, and
          attribution notices from the Source form of the Work,
          excluding those notices that do not pertain to any part of
          the Derivative Works;
```

No big deal - please add a line to each file where you have used our code, and provide a copy of the Apache license in the root of the repo. 

Many thanks.

**Comment by ChenMnZ** [comment]
Hi @jameshensman,

Thanks for your great work of QuaRot, and also thanks for your kindly reminder.

I have add the root Licence, and add code source to each related file.

**Comment by jameshensman** [comment]
Thanks so much for the rapid response @ChenMnZ
