### ISSUE TITLE
Question about outlier kv-cache (quantization)

### ISSUE THREAD

**Issue by kimwin2** [ChenMnZ/PrefixQuant#12]
Thanks for your effort to make this quantization algorithm.

I am curious about the outlier token kv caching. From the paper I read, it seems that because the outlier tokens are pre-cached, when a new token arrives and goes through per-tensor activation quantization, the outliers will not be included in the quantization process. However, even if the cached outlier k,v are used for calculating attention (i.e., matmul(q,k^T)), wouldn't k also go through per-tensor quantization? In this case, since k includes the prefix outlier token, I believe the scale value during the quantization process would increase. Is there anything wrong with my understanding?

Thanks for your reply in advance!

**Comment by ChenMnZ** [comment]
We do not quantize the prefixed tokens in KV cache, to facilitate per-tensor quantization of remained KV cache.

**Comment by 01000-you** [comment]
So, isn't it processing the prefixed tokens as full precision during the attention operation?

**Comment by XA23i** [comment]
> So, isn't it processing the prefixed tokens as full precision during the attention operation?

Tokens except special tokens are quantized by per-tensor static quantization, and thoese special tokens are from pre-computed cache and remains full-precision. So tensor K/V contains full-precision values and the attention operation also contains full-precision operations.  Does it make sense, I am not sure.
