### ISSUE TITLE
Question for quantization of prefix tokens

### ISSUE THREAD

**Issue by ponytaill** [ChenMnZ/PrefixQuant#15]
Hi, thanks for your work. I am very interested in your research.
I would like to ask how PrefixQuant quantizes the kv cache corresponding to prefix tokens? Is it the same as kv quantization methods of other general tokens?

**Comment by ChenMnZ** [comment]
Prefixed KV cache maintains as FP16.

**Comment by ponytaill** [comment]
> Prefixed KV cache maintains as FP16.

Thanks for your quick reply! I think I need to read the code again:)
