### ISSUE TITLE
question about SpinQuant

### ISSUE THREAD

**Issue by github-yizhang** [ChenMnZ/PrefixQuant#2]
hello! this work is very awesome! after reading your paper, I still have some questions.
1. it seems PrefixQuant is built based on SpinQuant，not Quarot? 
2. do PrefixQuant need training rotation matrix R1,R2 before quantization like SpinQuant? or PrefixQuant just insert rotation like SpinQuant and R1,R2,R3,R4 are hadamard matrix all the time?
3. when calculating the number of outlier tokens，the initial tokens are included or not?
4. how are the quantization parameters set? does it look like OmniQuant? 
great work and look forward to your reply.

**Comment by ChenMnZ** [comment]
1. yes， we follow spinquant to set the placement of rotation
2. No training of hadamard matrix. PrefixQuant insert rotation like SpinQuant and R1,R2,R3,R4 are always hadamard matrix.
3. We do not include initial tokens when calculating the frequency of outlier tokens.
4. It does not like OmniQuant. In PrefixQuant, weight uses per-channel symmetric quantization. KV cache uses per-head symmetric static quantization for 4-bit and per-tensor symmetric static quantization for 8-bit. Activation (inputs of linear layers) uses per-tensor static quantization.

**Comment by ChenMnZ** [comment]
3. when calculating the number of outlier tokens，the initial tokens are included
4. Yes,  you can refer sec. 5.2 in paper for details.

**Comment by brisker** [comment]
@ChenMnZ 
Regarding the prefix token strategy, will that also benefit dynamic per-token activation quantization , not only per-tensor-static? Any experiments?
