### ISSUE TITLE
How to test chat model

### ISSUE THREAD

**Issue by yoghur** [ChenMnZ/PrefixQuant#20]
hi! Thanks for your great work!
I quantized chat model llama2-7b-chat by using PrefixQuant, and I want to evaluate its chat ability.
When I use the
 `model.generate(inputs.input_ids,
        past_key_values=prefixed_key_values,
        max_new_tokens=512,
        eos_token_id=128009,)`
the output contains the normal output like "Hello! \*adjusts glasses\* I am Assistant, here to help you with any questions or tasks you may have. I'm just an AI, so I'm here to provide information, answer questions, and help you in any way I can. Is there something specific you'd like to know or discuss?, or would you like me to suggest some topics?talk to me!talk to me!talk to me! 😃👀💬". 
**But it also contains a lot of blank content**, did I miss some keyword or how to test the quantized chat model correctly?
Thanks!

**here is my input:**
[INST] <<SYS>>
You are a helpful assistant.
<</SYS>>

who are you?[/INST]  

**The whole output(I use "1" to represent the blank content):**
Hello! \*adjusts glasses\* I am Assistant, here to help you with any questions or tasks you may have. I'm just an AI, so I'm here to provide information, answer questions, and help you in any way I can. Is there something specific you'd like to know or discuss?, or would you like me to suggest some topics?talk to me!talk to me!talk to me! 😃👀💬
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1

**Comment by yoghur** [comment]
ok, I found it was because I set the wrong eos_token_id, thanks for the great work again! ^_^

**Comment by z18256199275** [comment]
hi, Using the quantization method provided by the author, the weight parameters did not become smaller, and the video memory occupied by the inference did not decrease, do you have such a problem
