### ISSUE TITLE
why add attention sink token to K/V cache can reduce outlier?

### ISSUE THREAD

**Issue by geqian-9192** [ChenMnZ/PrefixQuant#3]
Thank you for your job! I have tried on llama3-8B and it works well on W4A4KV4, but I want to know why add attention sink token to K/V cache can reduce outlier. I tried to explain it on softmax and value compuation, but when add BOS token in K/V cache, the output may not change. Wish your explaination.

**Comment by ChenMnZ** [comment]
For example, one [BOS] token will cause outlier in the input of down_porj layer.

Then, if you prefix such [BOS] token in KV cache in advance,  LLMs do not required to calculate again in the down_proj layer due to the auto-regressive inference mechanism. Therefore, there is no new outliers during inference.

**Comment by geqian-9192** [comment]
> For example, one [BOS] token will cause outlier in the input of down_porj layer.
> 
> Then, if you prefix such [BOS] token in KV cache in advance, LLMs do not required to calculate again in the down_proj layer due to the auto-regressive inference mechanism. Therefore, there is no new outliers during inference.

I can understand prefixing [BOS] token can reduce the input activation range of down_proj layer. But I have a new question, by learning  your code, the prefix token is not quantized  and keep fp16. But I check the max value of those tokens in model llama3-8b is 4, so can we quantize [BOS] token with other tokens in KV cache?

**Comment by ChenMnZ** [comment]
The answer is no.

As shown in Figure 3 in the paper, the prefixed KV tokens have some lower outliers, indicating that the value range of these prefixed KV tokens is significantly smaller than other tokens. Therefore, prefixed tokens can not share same quantization parameters with normal tokens.
