### ISSUE TITLE
How to skip layernorm fusion

### ISSUE THREAD

**Issue by lonleyodd** [ChenMnZ/PrefixQuant#5]
Thank you for your work; it's really helpful!

In your implementation, LayerNorm is fused into the embedding or linear layers. I tried to test the rotation and prefix methods on the original model, so I skipped the LayerNorm fusion by removing the fuse_layer_norms code and did not apply the QuantRMSNorm replacement, as shown below. However, when testing on WikiText-2, the perplexity (PPL) score came out to be 31994.6015625. I'm wondering if there might be special process with the Rotation step. How can I skip fusion process?

<img width="1145" alt="image" src="https://github.com/user-attachments/assets/ef91fd9d-0cd0-4a10-b550-1ac8200b7ed2">
<img width="833" alt="image" src="https://github.com/user-attachments/assets/c2232e30-561b-47e9-b01e-6baa3bcd5073">
<img width="1135" alt="image" src="https://github.com/user-attachments/assets/99ba9cc9-3133-4c6c-b762-298130ce5a1f">

**Comment by ChenMnZ** [comment]
If you want to use rotation, you must activate normalization fusion for computational invariance.

You can refer paper "[Slicegpt: Compress large language models by deleting rows and columns](https://arxiv.org/abs/2401.15024)" for detailes.

**Comment by lonleyodd** [comment]
> If you want to use rotation, you must activate normalization fusion for computational invariance.
> 
> You can refer paper "[Slicegpt: Compress large language models by deleting rows and columns](https://arxiv.org/abs/2401.15024)" for detailes.

well，I‘m just confuesd by the code `W_ - W_.mean(dim=-1, keepdim=True)`  after embedding，in RMSLayernorm like LLama2, there is no mean operation

**Comment by ChenMnZ** [comment]
Yeah, this can be deleted.

I just use the code from QuaRot. You can refer https://github.com/spcl/QuaRot/issues/7 for more detailes.
