### ISSUE TITLE
Question about various prefix values on original Model

### ISSUE THREAD

**Issue by lonleyodd** [ChenMnZ/PrefixQuant#8]
I tested various of  kvcache values on original model in FP16, but the results fluctuated, with some showing significant variations，like arc_e,arc_c.  I wonder if that's normal? 
![image](https://github.com/user-attachments/assets/c33e4be5-b2e2-4dc0-807d-b0a348c0bd34)

**Comment by ChenMnZ** [comment]
The small fluctuation in zero-shot tasks with prefix tokens is normal.
